# define port and backend of this instance
port = 42069
backend = "wlroots"

# example configuration

# define a client on the right side with host name "iridium"
# [left]
# # hostname
# host_name = "iridium"
# # optional ip address
# ip = "192.168.178.141"
# # optional port (defaults to 42069)
# port = 42069

# define a client on the left side with ip 192.168.178.189
#
# when an ip address is specified, it takes priority
# and host_name can be omitted
[right]
ip = "192.168.178.172"
port = 42069
