# example configuration

# optional port
port = 4242

# define a client on the right side with host name "iridium"
[right]
# hostname
host_name = "iridium"
# optional ip address
ip = "192.168.178.141"
# optional port (defaults to 4242)
port = 4242

# define a client on the left side with IP address 192.168.178.189
#
# when an IP address is specified, it takes priority
# and host_name can be omitted
[left]
ip = "192.168.178.189"
